Repository astral-sh/ruff-action, pull requests merged in 2024-12, with the labels that each got.

#17 Convert from composite to typescript
  .editorconfig
  .gitattributes
  .github/dependabot.yml
  .github/workflows/actionlint.yml
  .github/workflows/check-dist.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/python.yml
  .github/workflows/release-drafter.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .github/workflows/update-known-checksums.yml
  .github/workflows/update-major-minor-tags.yml
  .gitignore
  .pre-commit-config.yaml
  CODEOWNERS
  README.md
  __tests__/fixtures/checksumfile
  __tests__/fixtures/malformed-python-project/README.md
  __tests__/fixtures/malformed-python-project/pyproject.toml
  __tests__/fixtures/malformed-python-project/src/malformed_python_project/__init__.py
  __tests__/fixtures/malformed-python-project/src/malformed_python_project/hello_world.py
  __tests__/fixtures/python-project/README.md
  __tests__/fixtures/python-project/pyproject.toml
  __tests__/fixtures/python-project/src/python_project/__init__.py
  __tests__/fixtures/python-project/src/python_project/hello_world.py
  action.yml
  action/main.py
  biome.json
  dist/ruff-action/index.js
  dist/update-known-checksums/index.js
  package-lock.json
  package.json
  pyproject.toml
  release-drafter.yml
  src/download/checksum/checksum.ts
  src/download/checksum/known-checksums.ts
  src/download/checksum/update-known-checksums.ts
  src/download/download-version.ts
  src/ruff-action.ts
  src/update-known-checksums.ts
  src/utils/constants.ts
  src/utils/inputs.ts
  src/utils/platforms.ts
  tsconfig.json
Labels: breaking-change

#21 README.md: astral-sh/ruff-action@v1 --> v2
  README.md
Labels: documentation

#22 Move release-drafter.yml to .github
  .github/release-drafter.yml
Labels: ci

#25 Add lint error in malformed python project
  .github/workflows/test.yml
  __tests__/fixtures/malformed-python-project/src/malformed_python_project/hello_world.py
Labels: ci

#24 Set output format to github
  dist/ruff-action/index.js
  src/ruff-action.ts
Labels: bugfix

#26 Add problem matchers
  .github/matchers/check.json
  .github/matchers/format.json
  dist/ruff-action/index.js
  src/ruff-action.ts
Labels: enhancement

#32 Replace toml parsing library
  dist/ruff-action/index.js
  package-lock.json
  package.json
  src/utils/pyproject.ts
Labels: bugfix

#33 Bump eifinger/actionlint-action to v1.8.0
  .github/workflows/test.yml
Labels: dependencies

#35 update readme to v3
  README.md
Labels: documentation
