Repository astral-sh/ruff-action, pull requests merged in 2025-01, with the labels that each got.

#58 Fix Markdown link to Install the latest version
  README.md
Labels: documentation

#62 Fix compiled known versions
  dist/ruff-action/index.js
  dist/update-known-checksums/index.js
Labels: ci

#66 Read the `[project.optional-dependencies]` and `[dependency-groups]` tables
  .github/workflows/test.yml
  README.md
  __tests__/fixtures/pyproject-dependency-groups-project/README.md
  __tests__/fixtures/pyproject-dependency-groups-project/pyproject.toml
  __tests__/fixtures/pyproject-dependency-groups-project/src/pyproject_dependency_dev_project/__init__.py
  __tests__/fixtures/pyproject-dependency-groups-project/src/pyproject_dependency_dev_project/hello_world.py
  __tests__/fixtures/pyproject-optional-dependencies-project/README.md
  __tests__/fixtures/pyproject-optional-dependencies-project/pyproject.toml
  __tests__/fixtures/pyproject-optional-dependencies-project/src/pyproject_dependency_dev_project/__init__.py
  __tests__/fixtures/pyproject-optional-dependencies-project/src/pyproject_dependency_dev_project/hello_world.py
  dist/ruff-action/index.js
  src/utils/pyproject.ts
Labels: enhancement
