Repository astral-sh/ruff-action, pull requests merged in 2025-05, with the labels that each got.

#134 Inform user of unsupported old version
  .github/workflows/test.yml
  README.md
  dist/ruff-action/index.js
  src/ruff-action.ts
Labels: documentation

#142 docs: Explain that the default behaviour is ruff check
  README.md
Labels: documentation

#150 Add support for pep440 version specifiers
  .github/workflows/test.yml
  README.md
  dist/ruff-action/index.js
  package-lock.json
  package.json
  src/download/download-version.ts
Labels: enhancement

#151 Check that all jobs are in all-tests-passed needs
  .github/scripts/check-all-tests-passed-needs.ts
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: ci

#152 Bump dependencies
  dist/ruff-action/index.js
  dist/update-known-checksums/index.js
  package-lock.json
  package.json
Labels: dependencies
